### ISSUE TITLE
Warning text Advanced Parameters/Particles Dissolution

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1103]
After the new parameter `Enable supersaturarion` was introduced (#1100), the actual warning text (s. screen below) must be extended with something like this:
"_Enabling supersaturation only makes sense in combination with particles dissolution.
 If enabled for other kinds of dissolution... (dangerous/useless/bla bla)_"

@sfrechen @KatrinCoboeken @AndreDlm Please provide new warning text
![grafik](https://user-images.githubusercontent.com/25061876/52797222-ba838880-3075-11e9-94cd-612e4b976671.png)

**Comment by msevestre** [comment]
@Yuri05 Was introduced? is this already implemented ?

**Comment by Yuri05** [comment]
Not yet, it will be implemented with #1100

**Comment by sfrechen** [comment]
First draft (to be refined):
"Enabling supersaturation should always and only be allowed in combination with particle dissolution formulations otherwise disabled.  Enabling in case of other formulations would result in a lack of any solubility limitation."

**Comment by AndreDlm** [comment]
Sounds good! A slightly refined suggestion would be: "Enabling supersaturation inactivates the limit of how much solute can be dissolved. It should and only be allowed in combination with particle dissolution formulations otherwise disabled. Enabling in case of other formulations results in a lack of the solubility limit and hence in infinitely soluble solutes."
