### ISSUE TITLE
Use sum formula in base implementation where possible

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#1347]
See e.g. https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/531

This should also be done for:
- [x] Lung blood flow rate (see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1346)
- [x] Organism|Endogeneous IgG|Endosome|Volume
- [x] Organism|Endogeneous IgG|Interstitial|Volume
- [x] Organism|Endogeneous IgG|Plasma|Volume
- [x] Organism|Endogeneous IgG|Lymph flow rate
- [x] Organism|Endogeneous IgGFluid recirculation flow rate
- [x] Neighborhoods|EndogenousIgG_int_EndogenousIgG_pls|Surface area (plasma/interstitial)
- [x] FcRn binding MOLECULE in endosomal space
- [x] FcRn binding MOLECULE in interstitial
- [x] FcRn binding MOLECULE in plasma

more?

**Comment by msevestre** [comment]
@StephanSchaller I like this idea
We need however to decide, what criteria to use in order to build each formula
For example, `Organism|Endogeneous IgG|Endosome|Volume`
Which parameters will be part of this formula? (this needs to be expressed dynamically such as all parmaeter in a container with Tag xxx.)


This needs to be done for all formulas
If you could map that out, (of have someone do it....) we could try to implement it

**Comment by StephanSchaller** [comment]
@msevestre, I can (or get someone to) do this.

**Comment by msevestre** [comment]
Awesome
