### ISSUE TITLE
Overwrite of MoBi-Export to PK-Sim by User defined variability?

### ISSUE THREAD

**Issue by ClaireGrube** [Open-Systems-Pharmacology/PK-Sim#1376]
Dear all,

I have some troubles with the export of a parameter. I have defined a time dependency on that parameter in MoBi using a formula in "Parameter Start Value" like this: Time>x?a:b
It all works fine in MoBi, however when I export it into PK-Sim I think the User defined variability is overwriting the previously defined equation in MoBi.
So, is there a possibility to define a variability directly in Mobi using a standard deviation (SD) like this:
Time>x?a*SD:b*SD1

Thanks to all the comments. Kind regards & merry christmas everyone,
CG

**Comment by msevestre** [comment]
@ClaireGrube If you have defined some user-defined variability, you need to remove it indeed. 
Or are we talking about a parameter defined in the population? In that case, you need to remove it from the population. This can be easily done by exporting the population to CSV, removing the column matching the parameter of interest, and reimporting the population from CSV.

If you can attach an example of what your issue is (for example by creating the same situation using a standard pksim project), I might be able to help more

Michael

**Comment by msevestre** [comment]
@ClaireGrube Closing. Please reopen if you need more help. Also I'd suggest asking questions in the Forum for greater visibility
