### ISSUE TITLE
Discrepancy in half-life between single and multiple doses

### ISSUE THREAD

**Issue by adriankhoei** [Open-Systems-Pharmacology/PK-Sim#1510]
Hi everyone,

I am trying to create a PBPK model for a drug with half-life of 20 to 30 days. 

The healthy adult volunteer model for single dose predicts very well for both oral and IV routes of administration in simulations up to 130 days, and the half-life is 32 to 33 days in this scenario. But as I try multiple dosing (BID for 7 days) for the same patient with the same parameters, I get a half-life of 0.67 days for both 14 and 140 days simulation. 

I checked all the parameters including partition coefficients under distribution section, and everything is the same.

Large portion of the PK is influenced by a dynamic between a protein binding partner and the parent drug.

So, does anyone know if this is due to a saturation problem or what can possibly be the issue?

I have attached the corresponding PK profiles below.

Thank you,

Adrian

Multiple dose simulation up to 14 days
![1](https://user-images.githubusercontent.com/45637069/85347706-3a153900-b4ae-11ea-9d5a-4ed0ff2eda93.PNG)

Multiple dose simulation up to 140 days
![4](https://user-images.githubusercontent.com/45637069/85347716-40a3b080-b4ae-11ea-833d-65b48408ebef.PNG)

Single oral dose, simulation of parent drug in blood and urine
![2](https://user-images.githubusercontent.com/45637069/85347722-44cfce00-b4ae-11ea-9f00-27a930d2eba5.PNG)

Single IV dose, parent drug and metabolites in blood and parent drug in urine
![3](https://user-images.githubusercontent.com/45637069/85347744-53b68080-b4ae-11ea-924e-369291f520d3.PNG)

**Comment by adriankhoei** [comment]
Dear @msevestre,

Do you have any thoughts about this?

**Comment by StephanSchaller** [comment]
There might be an issue with the T1/2 calculations after multiple dosing.

Have you visually compared the terminal clearance phase if the decrease in concentration is the same?

**Comment by adriankhoei** [comment]
> There might be an issue with the T1/2 calculations after multiple dosing.
> 
> Have you visually compared the terminal clearance phase if the decrease in concentration is the same?

Hi @StephanSchaller 

Thank you for your reply.

By visually comparing the terminal phase, do you mean comparing something other that what we see on the graphs above? Could you please explain in more detail for me?

Thank you

**Comment by mnneely** [comment]
I think @StephanSchaller means that maybe the computed half-life of multi-dosing is in error, even though the simulation might be correct.  He's suggesting to look at the shape of the terminal curve and "manually" estimate half-life for the multi-dose simulation, or see if it declines similarly to the single-dose simulation. 

Based on a half-life of ~30 days, check to see if the concentration on day 50 of your multi-dose simulation is about half of the concentration on day 20.  If it is, the PK calculation is erroneous.  If is not, there's a bigger problem and the simulation is indeed "off".

**Comment by StephanSchaller** [comment]
Hi @mnneely , thanks for the clarification. That's exactly what I meant.

**Comment by adriankhoei** [comment]
> I think @StephanSchaller means that maybe the computed half-life of multi-dosing is in error, even though the simulation might be correct. He's suggesting to look at the shape of the terminal curve and "manually" estimate half-life for the multi-dose simulation, or see if it declines similarly to the single-dose simulation.
> 
> Based on a half-life of ~30 days, check to see if the concentration on day 50 of your multi-dose simulation is about half of the concentration on day 20. If it is, the PK calculation is erroneous. If is not, there's a bigger problem and the simulation is indeed "off".

Dear Dr. @mnneely , thank you for the clarification. 

I tested the curves as you mentioned and found out that half-life is around 3.7 days in multiple dosing while it is 25 days and 17 days in IV and oral routes, respectively.

**Comment by Aedginto** [comment]
Can you show me a picture of the 140 day multiple dose sim on a semi-log graph?

**Comment by adriankhoei** [comment]
> Can you show me a picture of the 140 day multiple dose sim on a semi-log graph?

Hi Dr. @Aedginto , thank you for your reply. Sure:

Single Dose 
![SingleDose](https://user-images.githubusercontent.com/45637069/88097137-98384900-cb4c-11ea-9085-3c17b2ea0af9.PNG)

BID for 7 days 
![MultipleDose](https://user-images.githubusercontent.com/45637069/88097151-9b333980-cb4c-11ea-9312-1ab4dc6306f5.PNG)

**Comment by Aedginto** [comment]
Please confirm that you are using the same partition coefficient algorithm for both sims. Distribution is different between the two simulations for some reason.

**Comment by adriankhoei** [comment]
Yes they are the same. I just emailed you my model file.

**Comment by msevestre** [comment]
@adriankhoei 

I think there are quite a few things going on

1. t1/2 is calculated for the FIRST INTERVAL where we extrapolate the last 10% of points. in your case, because you have multiple applications, the t1/2 for the first interval will be extremely FAST as there is no elimination phase that is taken into consideration (looking at the first interval only). So a value of 0.63 day makes sense. 

2. What you should really be looking at is, in fact, the other parameter **t1/2 tDLast-tEnd** which is calculated for the LAST interval and is, in my opinion, the only one that you can really compare with a single dosing

In your case the value is 387.57 hours so in days it would be **16 days.**

Note that there could also be some numerical artifact due to the way we extrapolate the points to calculate k. As said previously, we take the last 10% of points. But because the interval is so huge in your case, we in fact limit the number of points to 5000 per interval. So I can only assume that you may not have enough point at the end which might also affect the calculation of t1/2 for the last interval

Can you please put a screenshot of your resolution? Under Simulation => Settings
![image](https://user-images.githubusercontent.com/1041237/88108923-a780bc00-cb77-11ea-9c96-0c2ef71e3ad3.png)

**Comment by adriankhoei** [comment]
Hi @msevestre , thank you for the explanations.

Here's the screenshot you asked:
![1](https://user-images.githubusercontent.com/45637069/88112404-aabe7c80-cb64-11ea-917c-87434ce1ed98.PNG)

Regarding the large gap, I reduced the simulation time to one half-life (roughly 30 days) after the last dose for both single and multiple admins (i.e. 30 and 37 days for single and BID doses, respectively). t1/2 is 24.7 days for single dose and t1/2 tDLast-tEnd is 10.6 days for BID admin. I think the more-than-twice difference between half-lives is still unjustifiable. Also, Shorter simulations have shorter half-lives for both admins.

**Comment by msevestre** [comment]
> I think the more-than-twice difference between half-lives is still unjustifiable. 

Maybe. I am not a PK Expert. But at least, we have removed the assumption that PK-Sim was wrongly calculating t1/2 for MultipleDosing as suggested in some comments above. 

> Also, Shorter simulations have shorter half-lives for both admins.

Yes this is to be explained if you are not in the terminal phase. The slope will be different and therefore the t1/2 different

I can take a look at your project if you can send it to me (michael@design2code.ca) to see if I can spot anything suspicious

**Comment by StephanSchaller** [comment]
@adriankhoei , the two 140day plots you show above match the (terminal) T/12 calculations (the BID decreases to lower concentration levels over a shorter period of time).

But also the re-distribution after Cmax looks distinctively different, so as @Aedginto suggested, the two simulations might differ in other ways than just the dosing.

@msevestre, sorry for suggesting an error in the calculation. This was certainly a premature conclusion ;-)

**Comment by msevestre** [comment]
@adriankhoei I have checked both simulations and cannot spot any differences aside from the administration protocols.
It feels like some processes do behave differently. Is it possible that you are reaching some saturation of your process? I don't see anything wrong with the simulations. 
Maybe @Aedginto could comment?

**Comment by adriankhoei** [comment]
> @adriankhoei I have checked both simulations and cannot spot any differences aside from the administration protocols.
> It feels like some processes do behave differently. Is it possible that you are reaching some saturation of your process? I don't see anything wrong with the simulations.
> Maybe @Aedginto could comment?

Perhaps, but my dummy protein has a very high reference concentration, at least compare to what we have by default for hepatic enzymes, so it technically should not be the case. 

Also, it gives me different half-lives when trying single doses with different values as well, which makes it even more odd!

**Comment by Aedginto** [comment]
Hi Adrian,
I looked at your PK-Sim file and there is non-linearity in your model. The same profile as the multiple dose can be generated for the single dose is you give 10x the dose (try giving a single dose of 1550 mg and you will see). This is because of a couple of things: 1) while your liver enzymes have high Km values and are unlikely to be nonlinear in the concentration ranges of the simulations, your tubular secretion enzyme has a low Km and therefore likely leads to some of the non-linearity. I didn't play with it but you can by increasing the Km by 1000 and the Vmax by 1000 (outcome is the same ratio as before but without the non-linearity issue) and see if you get curve shape change at higher doses. 2) you have lysosome binding incorporated with low Kd. This is very likely the reason for your non-linearity. Check by removing this process and seeing if your simulation is still non-linear. You are getting the results you are getting because of one of these factors. 
Happy simulating! Andrea

**Comment by adriankhoei** [comment]
> Hi Adrian,
> I looked at your PK-Sim file and there is non-linearity in your model. The same profile as the multiple dose can be generated for the single dose if you give 10x the dose (try giving a single dose of 1550 mg and you will see). This is because of a couple of things: 1) while your liver enzymes have high Km values and are unlikely to be nonlinear in the concentration ranges of the simulations, your tubular secretion enzyme has a low Km and therefore likely leads to some of the non-linearity. I didn't play with it but you can by increasing the Km by 1000 and the Vmax by 1000 (outcome is the same ratio as before but without the non-linearity issue) and see if you get curve shape change at higher doses. 2) you have lysosome binding incorporated with low Kd. This is very likely the reason for your non-linearity. Check by removing this process and seeing if your simulation is still non-linear. You are getting the results you are getting because of one of these factors.
> Happy simulating! Andrea

Hello Dr. Edginton,
Thank you so much for taking your time looking at my model. Yes, that should be it! I will increase Km for tubular secretion and Kd for dummy protein to 1000 and see if the issue gets fixed. Adrian
