### ISSUE TITLE
PK-Sim 9 shuts down when trying to export data to csv

### ISSUE THREAD

**Issue by arketkar** [Open-Systems-Pharmacology/PK-Sim#1521]
As suggested earlier by OSP team, after updating my Windows 7 system (drivers, .NET framework), I could run simulations in PK-Sim version 9. However the moment I click on export PK analysis to csv or Export results to csv, it works couple of times, but then it shuts down. Is there any specific reason for this. I am facing the same problem with the portable version of version 9.

Some help will be certainly appreciated.

Thanks
Anant

**Comment by msevestre** [comment]
> Is there any specific reason for this.

Yes there is definitely something very specific going on with your machine. We are unable to understand the root cause. It seems to be triggered when accessing the file system (e.g. exporting results tries to open the standard message dialog box which crashes.)
It is a problem with your computer, clearly, as updating drivers and system improved the issue. 
Maybe some other drivers are still outdated. Very hard to tell.  Win7 is also a very old OS. While this should work in theory, you may want to move to a more robust system.

good luck

**Comment by arketkar** [comment]
Ok thanks @msevestre 

Based on your feedback I have requested my IT team to upgrade the OS to Windows 10. I hope that should work then.
I shall close this issue. 

Thanks again.
Anant
