### ISSUE TITLE
Autoinhibition in PK-Sim

### ISSUE THREAD

**Issue by Jesminna** [Open-Systems-Pharmacology/PK-Sim#1563]
It was indicated in the manual that "If an inhibition is set up for an enzyme or transporter, all processes with the same name will be linked and affected by the inhibition. An autoinhibition cannot be set-up because measured Ki values will already be altered due to autoinhibition."

Could you please explain this a little bit more regarding 1) why an autoinhibition (competitive inhibition) cannot be set up in PK-Sim? 2) why the measured Ki values will be altered due to autoinhibition?

If a drug shows autoinhibition (competitive inhibition) effect on an enzyme or transporter, how can I incorporate the autoinhibition effect in the model?
Thanks!

**Comment by sfrechen** [comment]
Hi @Jesminna 
It appears that the manual contains confusing information here with regard to "[...] autoinhibition cannot be set-up because measured Ki values will already be altered due to autoinhibition." I guess this sentence does not make sense.

Please note that there is no **auto-inhibition** in the narrow sense for a competitive inhibitor. A competitive inhibitor binds tightly to the enzyme of interest. If there is metabolism of the inhibitor via this enzyme, the kinetics of this are fully considered via Michaelis-Menten kinetics. In the case of a very model assuming simple binding to the enzyme to the one and only active site, then Km is actually equal to Ki. Km characterizes the metabolism of the inhibitor itself, Ki charcaterizes its effect on other substrates.

**Auto-inhibition** in the narrow sense may happen in case of mechanism-based inactivation. Here, the inactivator alters the amount of the enzyme which obviously has an additional effect on the rate of metabolism. This is automatically accounted for in PK-Sim if your inactivator features metabolism via the enzyme of interest.

Kind of auto-inhibition may also happen in case of competitive inhibitors if inhibiting metabolites are formed (typical example is itraconazole, please have a look here https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/tree/v9.1/Itraconazole). Of course, this can also easily be implemented in PK-Sim if your inhibitor features metabolism via the enzyme and of the metabolite features (competitive) inhibition of the enzyme.

Hope that helps
Sebastian

**Comment by Jesminna** [comment]
Thanks a lot for the detailed explanation! This is really helpful.

**Comment by msevestre** [comment]
@sfrechen @Yuri05 
Let's move this as an issue in the docs repo. It would be good to remove any confusion if we can
