### ISSUE TITLE
Plasma concentrations after multiple dosing

### ISSUE THREAD

**Issue by Lee21A** [Open-Systems-Pharmacology/PK-Sim#1571]
Hi everyone,

I found something strange in the PK-SIM result concerning plasma concentrations after multiple dosing.
For example, I simulated plasma concentrations after multiple dosing using Theophylline model.
Model: built in using Theophylline model
Administration Protocols: IV 100 mg, repeated for every 6 hr.
Simulation: using Kaumeier IV 100 mg simulations
  
![image](https://user-images.githubusercontent.com/72854911/95958236-d38ca000-0e3b-11eb-885f-562eb919445f.png)

 
![image](https://user-images.githubusercontent.com/72854911/95958271-df786200-0e3b-11eb-89d0-a79f1ded29b3.png)

You may see higher peak concentration after the first dosing compared with the second peak.
Based on the principle of superposition, it is hard to understand this feature. 
So, does anyone know the reason?

Thank you,

Lee

**Comment by StephanSchaller** [comment]
Yes, the reason is the resolution of your plotted curve.

The curve is made up of single points which are connected by lines. The points are set in such a way for your case, that they miss the peaks. So the peaks are there, you are just not seeing them as the plot resolution is too low...

Try increasing resolution here:
![image](https://user-images.githubusercontent.com/25477643/96520470-76478300-126f-11eb-86c7-a7f9be17fd29.png)

**Comment by Lee21A** [comment]
@StephanSchaller , Clear answer. Thank you very much. 

Lee
