### ISSUE TITLE
AUCR and CmaxR not calculated if formulation with more than 1 Particle bin used 

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1755]
In the attached file I wanted to calculete AUCR and CMaxR in the simulation" DDI Treatment - Itraconazole/Midazolam - Prueksaritanont 2017_particle50mg". But all I see after clicking on the triangle button, that it is calculating for some time. then it stops and nothing chnged. No AUCR or Cmax R is visible. unlike for the other simulation using Solution or default particle 10 µM. 
Is that normal or a bug?
[Test-AUCR-calc.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6466058/Test-AUCR-calc.zip)

![image](https://user-images.githubusercontent.com/25585248/117973569-db0e1c00-b32c-11eb-9283-70cd9cdb1984.png)

**Comment by Yuri05** [comment]
in v10, the following entries show the described behaviour:
![grafik](https://user-images.githubusercontent.com/25061876/129416119-a61eeeca-47ce-48a5-a990-2ee9cbf5989a.png)

**Comment by msevestre** [comment]
looking at this now

**Comment by msevestre** [comment]
This is interesting. It's happening to drugs that have NO protocol and are coming as part of a metabolization process in mutliple dosing. We are looking at the protocol to check what aprameter to use. Because we find nothing, we return the AUC_inf parameter which is not available for this one (multiple instances).

**Comment by Yuri05** [comment]
And which AUC is taken for AUCR if there is a protocol? AUC_tEnd_norm?
