### ISSUE TITLE
PK-Sim 10.0.137: no visible separator lines between organs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1762]
I thought it was already implemented - but I cannot see them (or is it just not "color blind people" friendly? :))
![grafik](https://user-images.githubusercontent.com/25061876/118816120-2aff5c80-b8b2-11eb-90b2-7fee39efed09.png)

**Comment by msevestre** [comment]
it's because you have used v10 before project conversion happened
Pleae delete your settings under V10 and try again

**Comment by msevestre** [comment]
They are copied over from one version to the next and then stay
So since you used an early version of v10, the conversion of colors did not happen and therefore you probably have the old one
Simply delete the settings (C:\Users\PavelTheGreat\AppData\Roaming\Open Systems Pharmacology\PK-Sim\10.0)  and PKsim 10 again

**Comment by PavelBal** [comment]
Maybe it makes sense to offer an option "reset settings" on installation? E.g. to make sure that when a bugfix for a version (10 -> 10.0.x) is released, the user can have a clean installation without the need to manually delete anything.

**Comment by msevestre** [comment]
bug fix would be 10.1. No issue here
