### ISSUE TITLE
Multiple project conversion

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#183]
[6.3.2_converted_to_7.1.0_example.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1022065/6.3.2_converted_to_7.1.0_example.zip)
The project attached was created with 6.3.2; after that opened and saved with 7.1.0.

If I open it with 7.1.0 next time, new entries "Protocol/Compound/Formulation are converted from 6.3.2 to 7.1.0" are added to the project history again

**Comment by msevestre** [comment]
This is the case when NO conversion happens but the versions were different. Since no conversion is happening, the objects are not marked with the HasChanged flag and as such they are not saved again. This is purely display issue with the history manager. In order to get that right, we need to change drastically how the conversion is being done to return, if an object was actually changed (not only compare versions). This is a bigger undertaking so nice to have, and definitely not 7.1
