### ISSUE TITLE
Bug in Import Observed Data: Importing of different dimensions for the dependent variable (Measurement) does not work

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1932]
The following error is thrown:

![image](https://user-images.githubusercontent.com/26569320/139434300-11e8ef98-97d0-407e-bffc-8ae79378c200.png)

**Comment by Yuri05** [comment]
* please attach an example or explain in detail how your data table(s) are constructed.
* how is the data importer configuration defined?

**Comment by sfrechen** [comment]
I noticed that it works in case we have add an additional grouping variable (such as DVID).

**Comment by sfrechen** [comment]
But I also noticed that the "naming elements" are somewhat mixed up, e.g.:
![image](https://user-images.githubusercontent.com/26569320/140748288-69939749-7aac-4d45-87c7-6bb6cc78f514.png)

Please find attached the data:
[Testdata_OSP10.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7497167/Testdata_OSP10.xlsx)

**Comment by msevestre** [comment]
@georgeDaskalakis Can you verify that this is fixed?

**Comment by georgeDaskalakis** [comment]
@msevestre the error with the mixup of the naming elements is fixed.

@sfrechen the initial description of the issue is not a false behaviour of the importer. When getting the units from a column, the dimension of the units for each data set has to be the same.  Otherwise it is totally impossible to create the data set. When you add the "DVID" grouping by, instead of generating 2 datasets that would have units of mixed dimension, you create 4 datasets. 

As you can see in the scrennshot here the first data set is of dimension "Concentration (mass)".

![image](https://user-images.githubusercontent.com/37107428/164457291-b6b30b83-3a57-4fc9-9151-8e074a31ea99.png)

Whereas the second one is of dimension "Fraction [%]"
![image](https://user-images.githubusercontent.com/37107428/164457412-13d2a43b-d7b9-4be5-bd68-a3c92d67fd73.png)


Without the grouping by those two dimensions would be mixed in one dataset, which is what the importer does not allow, giving the corresponding error message.
