### ISSUE TITLE
UX issue when importing in v11 (probably after change in dimensions)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2074]
Using latest PK-Sim with excel file from 

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1429

If I import the file, it looks like so
![image](https://user-images.githubusercontent.com/1041237/151367875-f9cdc871-992d-435c-9579-a01ad133506a.png)

If I select the correct column (why is a the column concentration not selected by default?)

![image](https://user-images.githubusercontent.com/1041237/151368030-4be5dcf0-331a-482b-be73-fea3c4c26150.png)

So the unit is not set somehow
If I open the combo, I see this
![image](https://user-images.githubusercontent.com/1041237/151368115-371a2f39-8c36-4ac6-84e7-6aad015feed1.png)

Now the units should have been preselected because it's availalbe in the column header. I realize that I need to exist the column. **THIS IS NOT OK** as I have explicitely selected. The event should be triggered on combox box selection. (we have a UxComboBoxRepositoryItem that does it for you. Please use this. If you are using it, it's something else)

THEN
If I reset the mapping, select the column and click tab it looks like so
![image](https://user-images.githubusercontent.com/1041237/151368482-ab74d260-1a47-423f-9980-9eec72aae8f6.png)

pmol/xx was selected (dimension abandance, first one in the list) even though it should be umol/l

Also everything is red even though it's set
![image](https://user-images.githubusercontent.com/1041237/151368901-a7c07c28-fa87-43e5-951f-219e596b1a81.png)

It should not be red anymore. If you want to tell the user to check the mapping, it should be done differently

**Comment by msevestre** [comment]
I don't even know how to get the tool to select the dimension for me. 
@Yuri05 @PavelBal Can you reproduce

**Comment by msevestre** [comment]
Note that error remains red, even after clicking the combobox
![image](https://user-images.githubusercontent.com/1041237/151369276-838d846a-c23a-4bc8-877b-b2afef49a182.png)

What is going on ??!

**Comment by PavelBal** [comment]
> why is a the column concentration not selected by default?

I guess the importer only can map columns that have the same name as mapping. So in this case, the column name should be "Measurement" (maybe with the unit) to be automatically recognized as such. If the importer does not find any column with the  name, it maps the first column with numeric values as "Measurement". I am fine with this behavior. Just name the column "Measurement".

> I don't even know how to get the tool to select the dimension for me.
I guess it only happens when you select "Reset mapping (based on current sheet)" and it selected the correct column (i.e., "Measurement [µmol/l]" for example). I agree that "guessing" the dimension should be performed every time user selects a column for "meausrement". Let's have a separate issue for this (I actually thought there was one...)

"Reset mapping" does some strange stuff, I agree.

**Comment by PavelBal** [comment]
What are you referring to? :D

**Comment by msevestre** [comment]
>guess it only happens when you select "Reset mapping (based on current sheet)"

No all the time

**Comment by PavelBal** [comment]
No, I mean that "guessing of dimension and units" is only performed when you reset based on current sheet..

**Comment by msevestre** [comment]
It should also be done when you select a column with unit in [] no?

**Comment by georgeDaskalakis** [comment]
This is fixed. 

The only behaviour from the issue description that still happens: The column that gets initially mapped to Measurement is still "MW" but correctly so. The importer is looking for "Measurement", does not find it and assigns the first numerical excel column it finds to Measurement.
