### ISSUE TITLE
Fraction expressed interstitial should be a formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2112]
In the Molecules-BB, the parameter "Fraction expressed interstitial" is set to `NaN`, and the overwritten by a formula in the PSV-BB:

![image](https://user-images.githubusercontent.com/25903040/156777039-2c2f62eb-ee30-4581-bf7a-dac9e4d7fc07.png)

![image](https://user-images.githubusercontent.com/25903040/156777085-5be9badc-1309-485a-9039-b7612b5e3203.png)

Should it not be defined as a formula in the Molecules-BB?

**Comment by msevestre** [comment]
Implementation: The formula will be defined in the Molecule and the Container Criteria will be "Interstitial" (or is it In Container "Interstitial")

@Yuri05 @PavelBal

**Comment by msevestre** [comment]
This now creates some issue in the PSV where parameters are created that we do not need

Fraction expressed intracellular | Organism | Gonads | Interstitial | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fraction expressed intracellular | Organism | Gonads | Intracellular | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Heart | Plasma | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Heart | BloodCells | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Heart | Interstitial | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Heart | Intracellular | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Kidney | Plasma | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Kidney | BloodCells | CYP2A6 |   |   | 1.00 |   |   | Fraction |  
Fraction expressed intracellular | Organism | Kidney | Interstitial | CYP2A6 |   |   | 1.00 |   |   | Fraction |  


because the value is not NaN but a number or a formula. Probably not a big deal because the parameter is not there and this will be removed with next version of MoBI

**Comment by PavelBal** [comment]
I don't undestand, maybe we can have a quick chat on monday... I thought we just define the tag `In Container: Intracellular" for the parameter "Fraction expressed intracellular"?

**Comment by msevestre** [comment]
Yep. But the way PSV are created is based on the logic "FOR ALL LOCAL PARAMETER, CREATE where value!=NaN"
So since value now is not NaN, we create everywhere. I have to see if we can check the logic of the Container definition as well when creating PSV but I am not sure that we have the info available

**Comment by msevestre** [comment]
I'd rather have a quick chat today

**Comment by msevestre** [comment]
ok I think this will work with condition for PSV As well. Updating core😊

**Comment by msevestre** [comment]
@Yuri05 
@PavelBal and I just had a chat. This works for expression interstial and intracellular but not for basolateral and apical because we have different formula. We created the apical only in some organs and not all of them. Then basolateral was used everywhere with the formula 1-apical if apical was present or 1 if not present. Suggetion, create apical everywhere so that we can use one formula only. Thus this would remove the two NaNs still there 

Suggestion

Suggetion
add fraction expressed apical in all interstitial organ (same as basolateral)
Formula for basolateral is always 1 - apical

tag for fraction expressed apical is "Interstitial"
tag for fraction expressed basolateral is "Intracellular"
