### ISSUE TITLE
11.1 Observed data mapping in a simulation: Default Scaling

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2385]
When we add an observed data set in a Parameter IDentification: Default Scaling is Log:
<img width="600" src="https://user-images.githubusercontent.com/25061876/199704671-0caad0ea-52d2-4b27-9823-53bb73dfd16f.png">

But when adding obs data to a simulation: default scaling is Linear:
<img width="600" src="https://user-images.githubusercontent.com/25061876/199704784-b860edb3-8a12-4be3-a58b-e2475518e55b.png">

Should we make it consistent and set the **default scaling for obs data in a simulation to Log** as well?

**Comment by PavelBal** [comment]
Consistent would be good, if we (@georgeDaskalakis ) understand how the defaults are selected. For PI, the default scaling is not always log but depends on the selected output. If we can easily re-use the code - than yes, it should also be used in the simulation.

**Comment by Yuri05** [comment]
>or PI, the default scaling is not always log but depends on the selected output. 

makes sense :)

It is defined here:
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/a3aa4aeaac5f62561d8c3f62f76e8a2a286599c0/src/OSPSuite.Core/Services/OutputMappingMatchingTask.cs#L63-L66

**Comment by PavelBal** [comment]
@georgeDaskalakis I think this will a be quick fix, right?

**Comment by msevestre** [comment]
This should absolutely be the same and the same code should be reused (not copy paste please).

**Comment by georgeDaskalakis** [comment]
I cannot reproduce it tbh. The code that you are pointing to @Yuri05 is also the exact same that is being used for the mapping in Simulation: it was moved from Parameter Identification to this newly created OutputMappingMatchingTask, and the simulation mapping happens here:

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/a3aa4aeaac5f62561d8c3f62f76e8a2a286599c0/src/OSPSuite.Core/Services/OutputMappingMatchingTask.cs#L59

when a new observed data is added. 

What does happen for sure is that when a matching output is not found the scaling is left to "linear", but this also happens when I add an output mapping to PI. Do you maybe have a project for me to reproduce?

**Comment by Yuri05** [comment]
>Do you maybe have a project for me to reproduce?

e.g. the project from https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2384

**Comment by georgeDaskalakis** [comment]
@Yuri05 yeap this does makes sense: in Simulations the default scaling is being calculated and set only when automatically mapping newly added observed data to an output, not when changing the output selection. Should not be that hard to add this, if I cna implement it fast I will.
