### ISSUE TITLE
Observer added in MoBi not available when simulation is exported to PK-Sim

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2485]
[01_ObserverPKSim.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10245329/01_ObserverPKSim.zip)

Simulation created in PK-Sim was sent to MoBi. In MoBi, new Container Observer **IsActive** was added:

![grafik](https://user-images.githubusercontent.com/25061876/208087285-1b925d05-f463-4bc5-a0b5-beda14f7b5f6.png)

In the simulation, this observer is created under Applications/Application_i:

![grafik](https://user-images.githubusercontent.com/25061876/208086353-12f40c1c-59d7-4989-8c91-19ad54b0dff8.png)

Then the new observed **IsActive** together with the standard PK-Sim obswerver **Fraction dissolved** was plotted

![grafik](https://user-images.githubusercontent.com/25061876/208086512-b1c4bb9b-7810-4ae2-9652-c7281abb70f0.png)

Simulation was exported to pkml and imported in PK-Sim.
Now in PK-Sim when selecting the curves to plot: the new IsActive observer is not available in the selection dialog and cannot be plotted:

![grafik](https://user-images.githubusercontent.com/25061876/208086951-97fd49a8-1cc4-42f1-99e1-29980c8889d9.png)

**Comment by Yuri05** [comment]
@msevestre FYI

**Comment by Yuri05** [comment]
P.S. If I define the new observer in MoBi not under Applications but under Organism: it works. I can plot the new observer in PK-Sim. 

![grafik](https://user-images.githubusercontent.com/25061876/208092956-23e0a084-7b0e-43de-b031-1216e787076e.png)

So seems PK-Sim restricts displayed quantities only to those stored under Organism?
If so: this should be changed.
![grafik](https://user-images.githubusercontent.com/25061876/208092755-03dad61f-39b3-459b-bdef-3d616b8ee0d9.png)

**Comment by msevestre** [comment]
Interesting

**Comment by msevestre** [comment]
@Yuri05 This is by design

![image](https://user-images.githubusercontent.com/1041237/208255900-b932165d-f3ab-4217-9408-fe7a5f5af2a1.png)


https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/Services/SimulationPersistableUpdater.cs#L87

We are hiding all observers under application except a few that are predefined. Maybe we should instead only hide the one we do not want to show.Like the the Concentration of the C1 under APP etc.. 

Not sure what should be the rule? Alternatively, we can just not hide anything.... Thoughts?

**Comment by Yuri05** [comment]
>We are hiding all observers under application except a few that are predefined. Maybe we should instead only hide the one we do not want to show.Like the the Concentration of the C1 under APP etc..

Yep, exactly this. I think we should show all application observers except `Concentration`
