### ISSUE TITLE
Different Cmax were calculated by different Partition coefficients selection 

### ISSUE THREAD

**Issue by miyayayayaa** [Open-Systems-Pharmacology/PK-Sim#2501]
Dear, 
      I found that if I changed the Partition coefficients selection, the predicited Cmax could have 2-fold range in my IV rat model. I wonder that whether it reasonable and why it happened? 

Best Regards,
Miya

![image](https://user-images.githubusercontent.com/98574201/210289375-3aa97a9f-350d-482e-a087-fbc45a5a0cbd.png)
![image](https://user-images.githubusercontent.com/98574201/210289382-9f2046e2-6922-46a1-9f04-6fd0a1703c8d.png)

**Comment by StephanSchaller** [comment]
This might be due to a change in the initial distribution phase and a too low resolution of your output/simulation curve.
Maybe change the resolution of your curve to 1 point/minute:

![image](https://user-images.githubusercontent.com/25477643/210329670-ee895443-0a8a-4bf2-b189-95415da8da7c.png)

**Comment by JanSchlender** [comment]
Hi Miya,
Cmax after iv bolus is dependent on volume of distribution (Vd) and dose. Since you administer the same dose in every run, your Vd drives the magnitude of Cmax. This is confirmed by the table you uploaded. In PBPK models, Volume of distribution is dependent on the distribution method (Vss = Vplasma + sum(Vorgan * Kp). Kp's will be computed by the distribution method. Thus, the results you uploaded are reasonable given the different assumptions of the distribution methods.
Best,
Jan

**Comment by StephanSchaller** [comment]
to add on @JanSchlender comment and put it in context to my answer: a high Vd leads to a faster rate of distribution in the very early phase thus affecting your "Cmax" (in quotation marks as it is only a Cmax after a few minutes and the real Cmax at T = 0 min is likely higher)

**Comment by miyayayayaa** [comment]
Thank you so much, @JanSchlender. I wonder whether any equations for Cmax calculated in PBPK model to explain "Cmax after iv bolus is dependent on volume of distribution (Vd). ".

Best, 
Miya

**Comment by StephanSchaller** [comment]
@miyayayayaa , the dependency is solely based on the slope of your first phase distribution and the resolution of your simulated curve. There is no "easy" equation for this.

**Comment by miyayayayaa** [comment]
Thank you so much. I got it. 

Best,
Min
