### ISSUE TITLE
Large molecules model: Parameter `Surface area (plasma/interstitial)` in `EndogenousIgG_int_EndogenousIgG_pls`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2547]
The parameter sums up all `Surface area (plasma/interstitial)`. However, the surface areas from mucosal tissues are not considered. Why?

@Yuri05 @Christoph27

**Comment by Christoph27** [comment]
Since the mucosa is subtracted from the respective parameters for large and small intestine, the surface areas from mucosal tissues are just missing and the equation for 'Surface area (plasma/interstitial)' in 'EndogenousIgG_int_EndogenousIgG_pls' should be supplemented with the mucosa values. @Yuri05, can you shift the label from question to bug?

**Comment by PavelBal** [comment]
So they are actually missing and should be added?

Then this proposal should fix it: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2549
