### ISSUE TITLE
V12: cannot create simulation with animals+Liver Plasma Clearance process

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2793]
If a compound contains Liver Plasma Clearance process: simulation with this compound and a non-human individual cannot be created
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/01783f20-2bd8-4408-b22b-ec5a68c307e8)

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/9fbb6d68-1f95-4c6e-9d9f-36138731d062)

**Comment by msevestre** [comment]
Ok this happens also with molecules and expression profile when you define an ontogeny
Does not make much sense but it's possible at the moment
The issue is that we have in the molecule an ontogenhy parameter (as we had before). It's now a TableFormulaWithXArgument that is pointing to an ontogenh table

Question. Should it be possible to define Ontogeny for an expression profile for an species that is not human? I don't think so
Then we could say

TableFormulaWithXArgument => If it points to a constant parameter, we always return the value, even if the xArgs cannot be resolved? Thougths

**Comment by Yuri05** [comment]
> Should it be possible to define Ontogeny for an expression profile for an species that is not human?

It should be possible only for age-dependent species - which is currently only human.



> TableFormulaWithXArgument => If it points to a constant parameter, we always return the value, even if the xArgs cannot be resolved?

agree
