### ISSUE TITLE
Endothelial surface area "Blood flow" - wrong values in the simulation?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2957]
The values AND formulas differ between the Individual and the actual simulation.

- Individual with "Endothelial surface area" calculation "Organ vascularization":
![image](https://github.com/user-attachments/assets/9a51dedd-2a5a-4968-ae8b-1dc8bc6afc18)

Uses the correct equation:
![image](https://github.com/user-attachments/assets/4beeea81-b89f-4687-95ae-9a71ca55e82b)

- Individual with "Endothelial surface area" calculation "Blood flow":
 
![image](https://github.com/user-attachments/assets/671057e7-3108-4ae6-b5b7-559921da640b)

Uses the correct equation, mind that the values are different (as expected):

![image](https://github.com/user-attachments/assets/0e6475d4-f9ea-4bca-9797-c0f100cab1be)

- Simulation using the individual with "Organ vascularization" - correct values (as in the individual):

![image](https://github.com/user-attachments/assets/d85890e2-556d-471b-9371-d623d9b00b6e)

## !!!!!
Simulation using the individual with "Blood flow" - WRONG formula AND the values are different from those in the individual!!

![image](https://github.com/user-attachments/assets/800b4470-db34-4d5d-885f-7339a7137492)

**Comment by Yuri05** [comment]
Cannot reproduce

**Comment by Yuri05** [comment]
OK, I can reproduce both in 11.3 and 12.0.
You need to have at least 2 individuals in the project with different calc methods for the endothelial surface area.
Example attached: [ICM.zip](https://github.com/user-attachments/files/16709073/ICM.zip)
Simulation S1_vasc is using the individual with "Organ vascularization" calc method and is properly created.
Simulation S2_blood is using another individual with "Blood flow" Calc method - and here the error occurs.

The problem is here:
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/9b650d7cea52592a912c1efffc3074e30e242b61/src/PKSim.Core/Services/ModelPropertiesTask.cs#L99-L104

https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/9b650d7cea52592a912c1efffc3074e30e242b61/src/PKSim.Core/Services/ModelPropertiesTask.cs#L123-L136

When creating a simulation, model properties (particularly calc methods) are filled in based on the individual/population which occurs to be the first in the create simulation dialog.
When switching to another individual population, those properties are **updated** based on the newly selected subject
(not sure why they are not just created from scratch).

And here (lines 129-131 above): if a calculation method for the given category already exists in the **model settings created for previously selected individual** - it's just kept and not replaced by the calc method from the new individual. This is the actual error.
So for my understanding it would be enough to 
a) either remove this updating part (lines 99-104) completely (however, not sure why this updating was done in the first place)
b) or in the update routine, remove existing calc methods instead of keeping them (replace `continue` in the line 131 with `modelProperties.RemoveCalculationMethod(calculationMethod)`)

@msevestre What do you think? Do you remember the reason for this updating part?
