### ISSUE TITLE
Observed data export for Reporting Engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#402]
tbd.

**Comment by KatrinCoboeken** [comment]
To use data, you have to provide two files: one file containing the data in the Nonmem format and a dictionary file, which documents the content of the data file.
The Nonmem file is a blank separated text file, column headers are used later on as Matlab variable names, and they must not contain special letters like blanks. All data columns used for figures and tables, have to be numerical and listed in the dictionary file (see below). For data filtering, these columns and additional ones can be used, the additional columns may also contain strings. But be careful, that these strings do not contain the column separator blank. A column must be either numerical or of type string.    

The dictionary is a csv file with the column separator “;”. In order to generate it, open in the templates directory (<SPM_RE_ROOT>\src\code\templates) the Excel file “NonmemFieldDicitonary.xlsx” and adjust the sheet tp Dictionary  according to your data, the sheet “readme” provides you with some more details on how to. Save the adjusted dictionary in format “*.csv” in your working directory.

**Comment by msevestre** [comment]
>The Nonmem file is a blank separated text file

do you mean TAB?

> In order to generate it, open in the templates directory (<SPM_RE_ROOT>\src\code\templates) the Excel file “NonmemFieldDicitonary.xlsx” 

We are going to generate the csv file directly. Can you describe the expected structure
Also if the NONMEN File is exported with TAB, why would we export this file with ";"? Should not that be somewhat consistent?

**Comment by Yuri05** [comment]
obsolete
