### ISSUE TITLE
Set weight of blood/tissue to invisible

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#428]
Once work on pregnancy population is finished, those parameters must be set to invisible

**Comment by msevestre** [comment]
Why? they can be defined as advanced parameter but I think those parameters are quite valuable don't you think?

**Comment by msevestre** [comment]
@Yuri05 I just talked to Andrea. 
According to her, those parameters are not relevant as is. HOWEVER they help understand the formula of Bodyweight that is otherwise very hard to comprehend. Her proposal was to let the parameter visible as it is now

I would add that the formula should be changed

BW = M_tissue + M_blood is not that great. I would suggest W_tissue or W_blood ?
Same with the SumFormula parameter that is used at the moment. Unless not feasible, I would proposed to rename it W and Not P

**Comment by Yuri05** [comment]
ok, let's keep them visible

>I would suggest W_tissue or W_blood or Weight_tissue + Weight_blood ?

Changed

>I would proposed to rename it W (or Weight even) and Not P

Cannot be changed without changing [dynamic formula implementation in OSPSuite.Core](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Formulas/DynamicFormula.cs#L33)
