### ISSUE TITLE
ValueOrigin: Refresh problem

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#574]
If a  ValueOrigin was changed e.g. in a building block and user updates a simulation from this BB
(and simulation view is opened) - value origin is not automatically updated in the simulation view.

**Comment by msevestre** [comment]
@Yuri05 I tried to make it work but for some reason, it does not refresh as expected. It might be because I am binding to a readonly value with devexpress. just clicking on the next cell is enough to get an update. I am not sure that we can actually fix this without changing the ValueORigin implementation.

**Comment by msevestre** [comment]
will be fixed when [ValueOrigin: Refresh problem #355](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/355) is merged
