### ISSUE TITLE
Individual: Default weight/heigth in snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#743]
If during creation of an Individual building block weight was not changed by user (means: weight is the **_default_** weight for the combination of inputs `{Population, Gender, Age, [GA]}`): weight should not be exported to snapshot.

Same for height.

**Comment by msevestre** [comment]
I don't understand this requirement. Why is this required?
We could argue that in that case, gender , population should not be saved if set to default as well. 
This removes information from the snapshot that is required to recreate explicitly the individual. Why do we want to be implicit here?

**Comment by msevestre** [comment]
And how should we know if the user changes the value or not? We don't even
have parameter? This is just a number in origin data.

Of course one could recreate an individual and see if it has the same
weight etc...but this is clearly over the top

**Comment by msevestre** [comment]
>And from this point of view there is no difference between default weight/heigth and e.g. default Volume fraction lipids.

Disagree. Height/weight are explicit input of the create individual. If they are not specified, the algorithm throws an exception. Volume fractions are purely and solely output of the create individual algorithm

**Comment by msevestre** [comment]
And there is also a mean age for a population. Why are we saving it if it's not changed?

**Comment by msevestre** [comment]
Same goes with GA. 
So in short, Height, Weight, GA and Age are **exactly** equivalent

**Comment by msevestre** [comment]
>MeanBW / MeanHeight ??
Not sure what you mean by that. We are saving an OriginData at that stage

At any rate,
Default_AGE = f0(Pop, Gender). This is all encapsulated in https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/08a5f407ff45fd0fdc09d3d0e2aa68d694a98545/src/PKSim.Core/Services/IndividualModelTask.cs#L9 more specifically

```
IParameter MeanAgeFor(OriginData originData);
IParameter MeanGestationalAgeFor(OriginData originData);
IParameter MeanWeightFor(OriginData originData);
IParameter MeanHeightFor(OriginData originData);
```

So if we go that route, my suggestion would be to be at least consistent and do the same for Age and GA

**Comment by Incei** [comment]
If I understood the discussion correctly, here's my opinion:

What will happen if our default values for a population (e.g. icrp pop) is updated due to new information from literature. Will we create a new population ICRP2, or will we update the existing ICRP. In case we update the existing ICRP, this will change the default wt-ht values for a certain age and gender right? If we then don't create a snapshot of the default set of values for bw-ht, then we will not be able to find back the original default values that easy. So in that case I would dentally want to snapshot them.

In case we do not overwrite the ICRP population, then I could live with not to snapshot it, but for sure we will need to snapshot age gender (and population) to find back the default values.
