### ISSUE TITLE
Load from Snapshot: usability

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#747]
When loading project from snapshot: first the window "Load project from snapshot" is shown; after that the user has to click on "..." to open a file dialog with snapshot file selection.
The second action must be done always anyway, so I would suggest to open the file dialog first.

**Comment by msevestre** [comment]
Agreed.
There is a lot that could be done in this view to improve overall usability
* ProgressBar
* Cancel
* Show message as formatted html instead of raw string so that one could visually differntiate the message via color. Alternatively, we could display the messages in a table so that one could filter items out etc..
