### ISSUE TITLE
Wrong formula dimension in new specific intestinal permeability alternative

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#779]
Problem and example described here: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/722#issuecomment-390428276

**Comment by msevestre** [comment]
As expected, this is the same issue as before (with dimension not being set properly for HIDDEN entities when creating them because of DB inconsistency)

It is also not a new bug since I could reproduce it with 7.2.2
See screenshot
![image](https://user-images.githubusercontent.com/1041237/40283450-6aea395c-5c4c-11e8-8287-47596fd638c9.png)

**Comment by msevestre** [comment]
Context: This bug as NO bearing whatsover on simulation results. This is just the formula that has the wrong dimension until the project is saved and loaded
