### ISSUE TITLE
Rifampicin template: all intestinal permeability values selected as default

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#981]
When loading the Rifampicin Compound from the template database, somehow both intestinal permeability values are selected as default:

![image](https://user-images.githubusercontent.com/25477643/47753571-4ffe3680-dc98-11e8-99e2-79f4d30f7357.png)

Also if trying to deselect the calculated value (first row) it does not get deselected (when clicking somewhere else, the selection reappears). Only by deselecting the second row, the values are deselected.

**Comment by msevestre** [comment]
I can confirm. How is this possible?!??
@Yuri05 How did you manage? Was it imported using snapshot or sthg?

**Comment by Yuri05** [comment]
>>Was it imported using snapshot 
apparently yes: #983

**Comment by tobiasK2001** [comment]
This bug is still present in the Rifampicin model loaded from here:
https://github.com/Open-Systems-Pharmacology/Rifampicin-Model.
Please reopen that issue!
This can lead to unnecessary confusion.
Interstingly the Rifampicin template available from PK-sim 8.0 is still a slightly differenet Version compared to Hanke et al 2018. This should be consolidated but without the bug;-)
